services:
  source:
    build: .
    restart: unless-stopped
    ports:
      - "45068:45068"
    volumes:
      - /srv/the-source:/var/lib/source
      - /mnt/data/gutenberg:/data/gutenberg
      - /mnt/data/lyrics:/data/lyrics
